nohup: ignoring input
INFO flwr 2023-10-08 23:55:41,024 | grpc.py:49 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-10-08 23:55:41,047 | connection.py:42 | ChannelConnectivity.IDLE
DEBUG flwr 2023-10-08 23:55:41,050 | connection.py:42 | ChannelConnectivity.CONNECTING
DEBUG flwr 2023-10-08 23:55:41,050 | connection.py:42 | ChannelConnectivity.TRANSIENT_FAILURE
INFO flwr 2023-10-08 23:55:41,163 | app.py:162 | Starting Flower server, config: ServerConfig(num_rounds=3, round_timeout=None)
INFO flwr 2023-10-08 23:55:41,183 | app.py:175 | Flower ECE: gRPC server running (3 rounds), SSL is disabled
INFO flwr 2023-10-08 23:55:41,183 | server.py:89 | Initializing global parameters
INFO flwr 2023-10-08 23:55:41,183 | server.py:276 | Requesting initial parameters from one random client
DEBUG flwr 2023-10-08 23:55:41,252 | connection.py:139 | gRPC channel closed
Traceback (most recent call last):
  File "unb_client.py", line 332, in <module>
    fl.client.start_numpy_client(
  File "/home/rtx4060ti3/anaconda3/envs/sfi2-ids/lib/python3.8/site-packages/flwr/client/app.py", line 288, in start_numpy_client
    start_client(
  File "/home/rtx4060ti3/anaconda3/envs/sfi2-ids/lib/python3.8/site-packages/flwr/client/app.py", line 201, in start_client
    task_ins = receive()
  File "/home/rtx4060ti3/anaconda3/envs/sfi2-ids/lib/python3.8/site-packages/flwr/client/grpc_client/connection.py", line 116, in receive
    server_message = next(server_message_iterator)
  File "/home/rtx4060ti3/anaconda3/envs/sfi2-ids/lib/python3.8/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/home/rtx4060ti3/anaconda3/envs/sfi2-ids/lib/python3.8/site-packages/grpc/_channel.py", line 950, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8080: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:8080: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-10-08T23:55:41.04775413+00:00"}"
>
INFO flwr 2023-10-08 23:55:42,064 | grpc.py:49 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-10-08 23:55:42,071 | connection.py:42 | ChannelConnectivity.IDLE
DEBUG flwr 2023-10-08 23:55:42,079 | connection.py:42 | ChannelConnectivity.READY
INFO flwr 2023-10-08 23:55:42,081 | server.py:280 | Received initial parameters from one random client
INFO flwr 2023-10-08 23:55:42,081 | server.py:91 | Evaluating initial parameters
INFO flwr 2023-10-08 23:55:42,081 | server.py:104 | FL starting
INFO flwr 2023-10-08 23:55:42,449 | grpc.py:49 | Opened insecure gRPC connection (no certificates were passed)
DEBUG flwr 2023-10-08 23:55:42,450 | connection.py:42 | ChannelConnectivity.IDLE
DEBUG flwr 2023-10-08 23:55:42,453 | connection.py:42 | ChannelConnectivity.READY
